apiVersion: v1
kind: ConfigMap
metadata:
  name: request-manager-config
data:
  mysql_url: {{ .Values.mysqlUrl }}:{{ .Values.mysqlPort }}
  aws_region: {{ .Values.aws_region }}
  aws_access_key_id: {{ .Values.aws_access_key_id }}
  aws_s3_upload_bucket: {{ .Values.aws_s3_upload_bucket }}
  aws_s3_download_bucket: {{ .Values.aws_s3_download_bucket }}
  rabbitmq_host: {{ .Values.rabbitmq_host }}  
  rabbitmq_port: {{ .Values.rabbitmq_port }}
  rabbitmq_ssl: {{ .Values.rabbitmq_ssl }}