apiVersion: v1
kind: Secret
metadata:
  name: request-manager-secret
data:
  mysql_user: {{ .Values.mysql_user }}
  mysql_password: {{ .Values.mysql_password }}
  aws_secret_access_key: {{ .Values.aws_secret_access_key}}
  aws_session_token: {{ .Values.aws_session_token }}
  rabbitmq_user: {{ .Values.rabbitmq_user }}
  rabbitmq_password: {{ .Values.rabbitmq_password }}